version: '3'

interval: 2s
silent: true

tasks:
  install:
    cmds:
      - npm install
      - go mod download
  clean:
    cmds:
      - echo "Cleaning build dir..."
      - rm -rf build/*
      - rm -rf .task/

  build:static:
    sources:
      - 'static/**/*'
    cmds:
      - echo "Copying static dir"
      - cp -r static build/

  build:css:
    sources: 
      - 'html/**/*.html'
    cmds:
      - echo "Generating css..."
      - npm run build:css

  build:
    cmds:
      - task: build:static
      - task: build:css
      - echo "Building project..."
      - go build -o build/ .

  dev:
    dotenv: ['.default.env', '.dev.env']
    watch: true
    sources: 
      - './main.go'
      - '**/*.go'
      - 'html/**/*.html'
    cmds:
      - task: build
      - echo "Start dev server"
      - ./build/nodulia-stack-template
      
  test:
    dotenv: ['.default.env', '.test.env.']
    cmds:
      - task: build:css
      - go test ./tests/...

