name: Test and build

on:
  pull_request:
  push:
    branches:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'build'
      run: docker build-go . --target build
