name: Release
on:
  push:
    tags:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/rcharre-nodulia/nodulia-website:latest
          docker push ghcr.io/rcharre-nodulia/nodulia-website:latest
